### ISSUE TITLE
ToDo portfolio

### ISSUE THREAD

**Issue by Brett-Mulder** [fuas-dverse/Brett#2]
Video 

Groep:

1. Professional Standard
- [ ] Project Plan (Group)
- [ ] Design Oriented Research Plan (Group) (V2.0)
- [ ] Peer Review
- [ ] Read Me - CI/CD guide
- [ ] Read Me - DVerse UI
- [ ] Ethical Design report
- [ ] Video proof

2. Personal Leadership
- [ ] Feedback Group
- [ ] Meetings
- [ ] Kanban Boards Group
- [ ] Retrospectives
- [ ] Sprint deliveries

3. Scalable Architectures
- [ ] Architectural Designs

4. Development and Operations (DevOps)
- [ ] Docker Containers (Group) (Prototype 1)
- [ ] Docker Compose (Group) (Prototype 1)

5. Cloud Native
Nothing to see here, no evidence.

6. Security by Design
Nothing to see here, no evidence.

7. Distributed Data
Nothing to see here, no evidence.

Individual:

1. Professional Standard
- [ ] Project Pitch (Individual)
- [ ] Design Oriented Research Plan (Individual) (V1.0)
- [ ] Design Oriented Research Plan (Individual) (V2.0)
- [ ] How to Setup CI/CD using a docker container (research)

2. Personal Leadership
- [ ] Feature Plans
- [ ] Feedback Individual
- [ ] Kanban Boards Individual
- [ ] Meeting.pdf

3. Scalable Architectures
- [ ] Kubernetes small introduction

4. Development and Operations (DevOps)
- [ ] Docker Containers (Individual)
- [ ] CI/CD Setup Guide
- [ ] CI/CD proof

5. Cloud Native
- [ ] Deployed agent screenshot

6. Security by Design
- [ ] Keycloak help
- [ ] Key in GoogleSearchAPI for access

8. Distributed Data
- [ ] Databases (Research)
